version: "3.9"
services:
  minerstat:
    build: .
    #image: ghcr.io/jonootto/flexpool-prometheus:master
    container_name: minerstat
    restart: unless-stopped
    environment:
      WALLET: $WALLET
      REFRESH: $REFRESH
    ports:
    - 8000:8000
