version: "3.9"
services:
  minerstat:
    #build: .
    image: jonootto/flexpool-influx:latest
    container_name: minerstat
    restart: unless-stopped
    environment:
      TZ: "Pacific/Auckland"
      INFLUX_IP: $INFLUX_IP
      INFLUX_PORT: $INFLUX_PORT
      INFLUX_USER: $INFLUX_USER
      INFLUX_PASS: $INFLUX_PASS
      ETHERSCAN_KEY: $ETHERSCAN_KEY
      WALLET: $WALLET
#    security_opt:
#      - seccomp:unconfined
