version: "3.9"
services:
  minerstat:
    #build: .
    image: jonootto/flexpool-influx:latest
    container_name: minerstat
    restart: unless-stopped
    environment:
      TZ: "Pacific/Auckland"
      ETHERSCAN_KEY: $ETHERSCAN_KEY
      WALLET: $WALLET
#    security_opt:
#      - seccomp:unconfined
